### ISSUE TITLE
Chroma style changing via config file doesn't work

### ISSUE THREAD

**Issue by wrobelda** [Wonderfall/hugo-WonderMod#11]
**Describe the bug**
You mention that to enable code styling, following should work:
```
markup:
    highlight:
        style: dracula
        noClasses: false
        guessSyntax: true
```

According to Hugo [docs](https://gohugo.io/content-management/syntax-highlighting/), however, if running with `noClasses: false`, one needs to generate the style by hand, e.g. `hugo gen chromastyles --style=monokai > syntax.css`. So  if I understand this right, your example is actually against the guidelines?

That having said, I tried with `noClasses: true` and changing the style to something else, but it has no effect no matter which one I choose. Something is wrong here?
